### PR TITLE
[WIP] Extended Python version of rbhtfinder

### PR DESCRIPTION
**Pull request by simonbray**

### CODE REVIEW

**Comment by DAlvGar** [comment]
I would add this a separate python version of the script instead of replacing the old perl one completely. What do you think?

**Comment by AlvaroSmorras** [comment]
In order to avoid problems with library versioning as what happened with sdtether and sdrmsd do you think it would be better to provide a miniconda installation along with rdock to use as an interpreter for the python scripts? Similary as how is done in Amber.

From our side we are also working on updating them to python3 (peter has a blog about sdtether). I agree with @DAlvGar that keeping the perl scripts is ok.

**Comment by simonbray** [comment]
> I would add this a separate python version of the script instead of replacing the old perl one completely. What do you think?

Fine for me either way, I am happy to go with whatever plan is decided for renaming / migrating scripts :)

**Comment by ggutierrez-sunbright** [comment]
the basic structure is ready, please update the branch and move your script to `rdock-utils/scripts/`
then we could approve and merge :+1:

**Comment by ggutierrez-sunbright** [comment]
Hi!
I see you moved the script, let me know when you feel like the PR is ready enough. we will merge and take it from there.  
It would be great if you could provided some predefined inputs and expected outputs so we can implement tests  

regards and thanks for your great work and interest,

@ggutierrez-sunbright

**Comment by simonbray** [comment]
> Hi! I see you moved the script, let me know when you feel like the PR is ready enough. we will merge and take it from there. It would be great if you could provided some predefined inputs and expected outputs so we can implement tests
> 
> regards and thanks for your great work and interest,
> 
> @ggutierrez-sunbright

Done. Thanks!

**Review by ggutierrez-sunbright — APPROVED** [review]

**Pull request merged**
